version: '3'
services:
  mariadb:
    image: mariadb:11.3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=vintly
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci


networks:
  default:
    driver: bridge # bridge network 안에서는 컨테이너 이름으로 통신할 수 있다.